language: java

jdk:
- openjdk8

script: mvn -DskipTests=true -B package --file pom.xml

after_success:
  - ls target
  - source script.sh

if: branch = master

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: $PLUGIN_JAR_PATH
  prerelease: $PRERELEASE
  draft: $DRAFT
  skip_cleanup: true
  on:
    branch: master