# TimeMine Configuration

# MySQL config options
mysql:
  username: "username"
  password: "password"
  host: "localhost"
  port: "3306"
  database: "database"

# General config options
timemine:
  # In seconds. How often the plugin should check for expired TimeMine blocks. <30 is not recommended.
  expired_block_reset_interval: 30
  prefix: "[TimeMine]"

# Mineables config section
#   Format:
#     TOOL_ENUM: (Can be any item in the game that you want to be able to the specified blocks)
#       - BLOCK_ENUM (Must be a breakable block)
#       - ANOTHER_BLOCK_ENUM (Can list as many blocks as you want which should be mineable by this block)
mineables:
  DIAMOND_PICKAXE:
    - DIAMOND_ORE
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - EMERALD_ORE
    - LAPIS_ORE
    - NETHER_QUARTZ_ORE
    - REDSTONE_ORE
  GOLD_PICKAXE:
    - DIAMOND_ORE
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - EMERALD_ORE
    - LAPIS_ORE
    - NETHER_QUARTZ_ORE
    - REDSTONE_ORE
  IRON_PICKAXE:
    - DIAMOND_ORE
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - EMERALD_ORE
    - LAPIS_ORE
    - NETHER_QUARTZ_ORE
    - REDSTONE_ORE
  STONE_PICKAXE:
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - NETHER_QUARTZ_ORE