name: TimeMine
version: 1.0.0-beta
author: Github/popatop15
website: www.indicacorp.net
main: net.indicacorp.timemine.TimeMine
api-version: "1.14"
commands:
  timemine:
    description: TimeMine base command.
    usage: "/timemine help"
    aliases: [tm]
permissions:
  timemine.admin:
    description: Default permission node. Allows all commands.
    default: op